version: '3.9'

services:
  download:
    build: ./services/download/
    profiles: ["download"]
    volumes:
      - ./data:/data

  comfy: &comfy
    ports:
      - "${WEBUI_PORT:-7860}:7860"
    volumes:
      - ./data:/data
      - ./output:/output
    stop_signal: SIGKILL
    tty: true
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #           - driver: nvidia
    #             device_ids: ['0']
    #             capabilities: [compute, utility]
    profiles: ["comfy"]
    build: ./services/comfy/
    image: sd-comfy:6
    environment:
      - CLI_ARGS=--cpu


